services:
  report-service:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      # Access http://localhost/
      - 8081:8081
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - microservice_network
networks:
  microservice_network:
    name: microservice_network
    driver: bridge